create table if not exists public.demands (
  id bigint generated by default as identity primary key,
  code text unique not null,
  title text not null,
  neighborhood text not null,
  owner text not null,
  status text not null check (status in ('pendiente', 'gestion', 'resuelto')),
  status_label text not null,
  history text not null,
  location_label text,
  map_x numeric,
  map_y numeric,
  lat numeric,
  lng numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.referents (
  id bigint generated by default as identity primary key,
  name text not null,
  neighborhood text not null,
  phone text not null,
  community_role text,
  influence text not null,
  meetings text not null,
  created_at timestamptz not null default now()
);

alter table public.referents
add column if not exists community_role text;

create table if not exists public.meetings (
  id bigint generated by default as identity primary key,
  title text not null,
  meeting_date date not null,
  neighborhood text not null,
  participant_names jsonb not null default '[]'::jsonb,
  attendee_count integer not null,
  topics text not null,
  location_label text,
  lat numeric,
  lng numeric,
  created_at timestamptz not null default now()
);

alter table public.demands enable row level security;
alter table public.referents enable row level security;
alter table public.meetings enable row level security;

drop policy if exists "Lectura publica demandas" on public.demands;
drop policy if exists "Carga publica demandas" on public.demands;
drop policy if exists "Lectura publica referentes" on public.referents;
drop policy if exists "Carga publica referentes" on public.referents;
drop policy if exists "Lectura publica reuniones" on public.meetings;
drop policy if exists "Carga publica reuniones" on public.meetings;

create policy "Lectura publica demandas"
on public.demands for select
to anon
using (true);

create policy "Carga publica demandas"
on public.demands for insert
to anon
with check (true);

create policy "Lectura publica referentes"
on public.referents for select
to anon
using (true);

create policy "Carga publica referentes"
on public.referents for insert
to anon
with check (true);

create policy "Lectura publica reuniones"
on public.meetings for select
to anon
using (true);

create policy "Carga publica reuniones"
on public.meetings for insert
to anon
with check (true);
